### ISSUE TITLE
FreeBSD compatibility

### ISSUE THREAD

**Issue by slegrand45** [Drup/ocaml-lmdb#27]
Not sure if it's really an issue but to install the opam package on FreeBSD 12 i had to explicitly set C_INCLUDE_PATH and LIBRARY_PATH:

`setenv C_INCLUDE_PATH /usr/local/include/`
`setenv LIBRARY_PATH /usr/local/lib/`

May be there is a standard way with opam or dune to avoid this manual setting?

**Comment by madroach** [comment]
On OpenBSD I added
``` sh
export CPATH=/usr/local/include:/usr/X11R6/include
export LIBRARY_PATH=/usr/local/lib:/usr/X11R6/lib
```
to ``/etc/profile``

That's why I probably never hit such issues.
If you find out how this is properly done please let me know.
