### ISSUE TITLE
Consider updating the opam package.

### ISSUE THREAD

**Issue by xekoukou** [Drup/ocaml-lmdb#28]
The api has changed so much that a new opam release might be necessary.

**Comment by sliquister** [comment]
I wanted to inquire about the status of this. I had looked at ocaml-lmdb a while ago, and was also surprised by the fact the opam package looked very different from the git master branch. I see https://github.com/Drup/ocaml-lmdb/pull/35 exists, but seems to have stalled.

**Comment by madroach** [comment]
resolved by https://github.com/ocaml/opam-repository/pull/16223

**Comment by sliquister** [comment]
Thanks!
