### ISSUE TITLE
not in opam?!

### ISSUE THREAD

**Issue by UnixJunkie** [Drup/ocaml-lmdb#4]
What is the show stopper?
Is it not production ready?

**Comment by Drup** [comment]
You're right, I should release. Handling some part of lmdb in a sound way is very painful, and so I don't do it. But the last version is decent at allowing users to create types of databases with various customizations.

**Comment by UnixJunkie** [comment]
If you have a simple example using string keys and values (to implement a persistent hashtbl), I'll take it.

**Comment by Drup** [comment]
https://github.com/Drup/ocaml-lmdb/blob/master/tests/simple_db.ml

**Comment by Drup** [comment]
Done!

**Comment by UnixJunkie** [comment]
I wrote dokeysto for the specific purpose I needed.
```
opam info dokeysto
[...]
Persistent hash table (i.e. in a file on disk) for string keys and string values.
```
